//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentRegistration
    {
        public int StudentId { get; set; }
        public string StudentName { get; set; }
        public int StaffId { get; set; }
        public string FatherName { get; set; }
        public string AadharNo { get; set; }
        public string MobileNo { get; set; }
        public string WhatsAppNo { get; set; }
        public byte Education { get; set; }
        public string StudentCode { get; set; }
        public System.DateTime RegsitrationDate { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public byte Status { get; set; }
    
        public virtual Staff Staff { get; set; }
        public virtual StaffLogin StaffLogin { get; set; }
        public virtual StaffLogin StaffLogin1 { get; set; }
    }
}
